version: '3.8'

services:
  app:
    build:
      context: ./app
    container_name: express-app
    expose:
      - "3000"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped
